// Cubic spline

// Copyright snsinfu 2020-2021.
// Distributed under the Boost Software License, Version 1.0.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.




using System;
using System.Collections.Generic;
using System.Diagnostics;


/*
* Specifies the boundary conditions used to determine the splines.
*/
enum BoundaryConditions
{
    Natural,
    NotAKnot,
};

// A spline_data defines a single piece of spline function:
//   f(t) = sum( a_k * (t - t_0)^k , 0 <= k <= 3 ).
// t_0 is the knot and a_0,...,a_3 are the coefficients.
struct SplineData
{
    public float knot;
    public float[] coefficients;
    public SplineData(int order)
    {
        coefficients = new float[order + 1];
        knot = 0;
    }
};

/*
 * Cubic spline functor for interpolating one-dimensional series of values.
 */
class CubicSpline
{
    // Order of the polynomial.
    const int order = 3;
        
    List<SplineData> _splines = new List<SplineData>();
    List<int> _bins = new List<int>();
    float _lower_bound;
    float _upper_bound;
    float _bin_interval;

    /*
     * Constructs a cubic spline function that passes through given knots.
     */
    public CubicSpline(
        List<float> t,
        List<float> x,
        BoundaryConditions bc = BoundaryConditions.Natural
    )
    {
        MakeSpline(t, x, bc);
        MakeBins();
    }

    /*
     * Evaluates the cubic splines at `t`.
     */
    public float GetValue(float t)
    {
        SplineData spline = FindSpline(t);

        float value = spline.coefficients[order];
        for (int i = order - 1; i >= 0; i--) {
            value *= t - spline.knot;
            value += spline.coefficients[i];
        }

        return value;
    }

    /*
     * Solves a tridiagonal system of equations.
     *
     * The arguments lower, diag, upper and rhs define the equations and must
     * be of the same length (say n). The i-th element of each vector specifies
     * the i-th linear equation, i = 0 to n - 1 from the top to the bottom.
     * lower and upper must be padded at lower[0] and upper[n - 1].
     *
     * The vectors are modified in-place. The solution is returned to rhs.
     */
    private void SolveTridiagonalSystem(
       float[] lower,
       float[] diag,
       float[] upper,
       float[] rhs
    )
    {
        int dim = rhs.Length;

        Debug.Assert(dim != 0);
        Debug.Assert(lower.Length == dim);
        Debug.Assert(diag.Length == dim);
        Debug.Assert(upper.Length == dim);

        // Elimination step.
        for (int i = 0; i < dim - 1; i++)
        {
            if (Math.Abs(diag[i]) >= Math.Abs(lower[i + 1]))
            {
                // Normal tridiagonal algorithm.
                float w = lower[i + 1] / diag[i];
                diag[i + 1] -= w * upper[i];
                rhs[i + 1] -= w * rhs[i];
                lower[i + 1] = 0;
            }
            else
            {
                // Pivoting. Here, we interchange the i-th row and the (i+1)-th
                // row, then eliminate. Unlike the other branch, the lower
                // triangular element lower[i+1] will remain. This affects the
                // back substitution step below.
                float w = diag[i] / lower[i + 1];

                float u = diag[i + 1];
                diag[i] = lower[i + 1];
                diag[i + 1] = upper[i] - w * u;
                lower[i + 1] = upper[i + 1];
                upper[i + 1] *= -w;
                upper[i] = u;

                float r = rhs[i];
                rhs[i] = rhs[i + 1];
                rhs[i + 1] = r - w * rhs[i + 1];
            }
        }

        // Back-substitution step.
        rhs[dim - 1] /= diag[dim - 1];

        for (int i_rev = 2; i_rev <= dim; i_rev++)
        {
            int i = dim - i_rev;
            if (i == dim - 2)
            {
                rhs[i] -= upper[i] * rhs[i + 1];
            }
            else
            {
                rhs[i] -= upper[i] * rhs[i + 1] + lower[i + 1] * rhs[i + 2];
            }
            rhs[i] /= diag[i];
        }
    }

    /*
     * Constructs spline segments `_splines` for given set of knot points.
     */
    private void MakeSpline(
        List<float> knots,
        List<float> values,
        BoundaryConditions bc
    )
    {
        if (knots.Count != values.Count) {
            Debug.Assert(false, "input lengths mismatch");
            return;
        }
        if (knots.Count <= 1) {
            Debug.Assert(false, "insufficient number of knots");
            return;
        }

        int n_knots = knots.Count;
        int n_segments = n_knots - 1;

        float[] intervals = new float[n_segments];
        float[] slopes = new float[n_segments];

        for (int i = 0; i < n_segments; i++) {
            var dt = knots[i + 1] - knots[i];
            var dx = values[i + 1] - values[i];

            if (dt <= 0) {
                Debug.Assert(false, "knots must be strictly increasing");
                return;
            }

            intervals[i] = dt;
            slopes[i] = dx / dt;
        }

        // Let M[i] be the second derivative of the i-th spline at the i-th
        // knot, i = 0,...,n where n is the number of segments. The vector M is
        // given by a tridiagonal system of equations:
        //
        // [ D[0] U[0]                      ] [ M[0]   ]   [ Y[0]   ]
        // [ L[1] D[1] U[1]                 ] [ M[1]   ]   [ Y[1]   ]
        // [      L[2] D[2] U[2]            ] [ M[2]   ]   [ Y[2]   ]
        // [      ...  ...  ...             ] [   :    ] = [   :    ]
        // [           L[n-1] D[n-1] U[n-1] ] [ M[n-1] ]   [ Y[n-1] ]
        // [                  L[n]   D[n]   ] [ M[n]   ]   [ Y[n]   ]
        //
        // We define the coefficients L, D, U and Y below and solve the
        // equations for M.

        float[] L = new float[n_segments + 1];
        float[] D = new float[n_segments + 1];
        float[] U = new float[n_segments + 1];
        float[] Y = new float[n_segments + 1];

        if (n_segments == 1) {
            // Natural (which gives a straight line) is the only sensible choice
            // if there is only one spline.
            bc = BoundaryConditions.Natural;
        }

        switch (bc) {
        case BoundaryConditions.Natural:
            // These coefficients are derived by assuming that the boundary
            // splines are linear.
            D[0] = 1;
            D[n_segments] = 1;
            break;

        case BoundaryConditions.NotAKnot:
            // These coefficients are derived by assuming that the boundary
            // splines are identical to their adjacent splines.
            {
                var h0 = intervals[0];
                var h1 = intervals[1];
                var s0 = slopes[0];
                var s1 = slopes[1];
                D[0] = h0 - h1;
                U[0] = 2 * h0 + h1;
                Y[0] = -6 * h0 / (h0 + h1) * (s0 - s1);
            }
            {
                var h0 = intervals[n_segments - 1];
                var h1 = intervals[n_segments - 2];
                var s0 = slopes[n_segments - 1];
                var s1 = slopes[n_segments - 2];
                D[n_segments] = h0 - h1;
                L[n_segments] = 2 * h0 + h1;
                Y[n_segments] = 6 * h0 / (h0 + h1) * (s0 - s1);
            }
            break;
        }

        // The remaining coefficients are derived from the spline conditions.
        for (int i = 1; i < n_segments; i++) {
            L[i] = intervals[i - 1];
            D[i] = 2 * (intervals[i - 1] + intervals[i]);
            U[i] = intervals[i];
            Y[i] = 6 * (slopes[i] - slopes[i - 1]);
        }

        // Solve the equations. Solution is returned to Y.
        SolveTridiagonalSystem(L, D, U, Y);
        var M = Y;

        // Derive the polynomial coefficients of each spline segment from the
        // second derivatives `M`.
        _splines.Clear();
        _splines.Capacity =n_segments;

        for (int i = 0; i < n_segments; i++) {
            SplineData spline = new SplineData(order);
            spline.knot = knots[i];
            spline.coefficients[0] = values[i];
            spline.coefficients[1] = slopes[i] - (M[i + 1] + 2 * M[i]) * intervals[i] / 6;
            spline.coefficients[2] = M[i] / 2;
            spline.coefficients[3] = (M[i + 1] - M[i]) / (6 * intervals[i]);
            _splines.Add(spline);
        }

        if (knots.Count > 0)
        {
            _lower_bound = knots[0];
            _upper_bound = knots[knots.Count - 1];
        }
    }

    /*
     * Builds a bin-based index `_bins` that is used to quickly find a spline
     * segment covering a query point.
     */
    private void MakeBins()
    {
        _bin_interval = (_upper_bound - _lower_bound) / (float)(_splines.Count);

        // We need to map uniformly-spaced bins to spline segments that may
        // not be uniformly spaced. Here `index` identifies a spline segment.
        // We iterate over bins and synchronize spline segments accordingly.
        int index = 0;

        for (int bin = 0; ; bin++) {
            var bin_edge = _lower_bound + _bin_interval * bin;

            while (index + 1 < _splines.Count && _splines[index + 1].knot <= bin_edge) {
                index++;
            }

            // Now, the lower edge of the bin is covered by the spline segment
            // at `index`.
            _bins.Add(index);

            if (index + 1 == _splines.Count) {
                break;
            }
        }
    }

    /*
     * Returns the spline segment that covers given point `t`.
     */
    private SplineData FindSpline(float t)
    {
        if (t <= _lower_bound) {
            return _splines[0];
        }
        if (t >= _upper_bound) {
            return _splines[_splines.Count-1];
        }

        int bin = (int)((t - _lower_bound) / _bin_interval);
        if (bin >= _bins.Count) {
            bin = _bins.Count - 1;
        }
        int index = _bins[bin];

        Debug.Assert(t >= _splines[index].knot);

        for (; index + 1 < _splines.Count; index++) {
            if (t < _splines[index + 1].knot) {
                break;
            }
        }
       
        return _splines[index];
    }
}

